name: CI - Android Tests

on: pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set Java SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Kotlin Tests
        working-directory: .
        run: |
          ./gradlew build
          ./gradlew test
          ./gradlew --stop
